# Generated by Django 3.1.1 on 2020-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=300)),
                ('Content', models.TextField()),
                ('Date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
